version: '3.9'
services:
  pg-db:
    # NOTE: Uncomment the line below if you are using Mac with m1/m2 chip
    platform: linux/x86_64
    container_name: pg-db
    image: postgres:13
    restart: always
    env_file: ./.env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: db
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - default

  t3-app:
    # NOTE: Uncomment the line below if you are using Mac with m1/m2 chip
    platform: linux/x86_64
    # NOTE: If you are NOT using a mac with an m1/m2 chip uncomment this line instead
    # platform: 'linux/amd64'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: 'clientvar'
    working_dir: /app
    ports:
      - $NEXTJS_APP_LOCAL_PORT:$NEXTJS_APP_DOCKER_PORT
    image: t3-app
    restart: always
    env_file: ./.env
    container_name: t3-stack-app
    depends_on:
      - pg-db
    stdin_open: true
    tty: true
    volumes:
      - ./src:/src
      - /node_modules
      - /.next
    networks:
      - default

volumes:
  postgres_data:
# volumes:
#   mysql-volume:
