version: "3.9"
services:
  mysql-db:
    # NOTE: Uncomment the line below if you are using Mac with m1/m2 chip
    # platform: linux/x86_64
    container_name: mysql-db
    image: mysql:latest # 5.7
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - mysql-volume:/var/lib/mysql:rw
      # - ./mysql-db:/docker-entrypoint-initdb.d/
    networks:
      - default

  t3-app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - $NEXTJS_APP_LOCAL_PORT:$NEXTJS_APP_DOCKER_PORT
      # - "3000:3000"
    image: t3-app
    # environment:
    #   - DATABASE_URL=database_url_goes_here

    restart: unless-stopped
    env_file: ./.env
    container_name: t3-stack-app
    depends_on:
      - mysql-db
    stdin_open: true
    tty: true
    volumes:
      - ./src:/src
      - /node_modules
      - /.next
    networks:
      - default

volumes:
  mysql-volume:
