import { type NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
// import { useState } from 'react';
import useStore from '~/store/useStore';

const Counter: NextPage = () => {
  const counter = useStore((state) => state.counter);
  const increase = useStore((state) => state.increase);

  return (
    <>
      <Head>
        <title>T3 App Sample</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#02326d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Count: {counter}
          </h1>

          <div>
            <button
              className="rounded bg-blue-500 px-4 py-2 font-bold text-white hover:bg-blue-700"
              onClick={() => {
                increase(1);
              }}
            >
              +
            </button>
          </div>
          <Link href="/">Home</Link>
        </div>
      </main>
    </>
  );
};

export default Counter;
