import { type NextPage } from 'next';
import Head from 'next/head';
import { useEffect } from 'react';
import { WorkTypeView, WorkOptionsView } from '~/pages/views';
import useStore from '~/store/useStore';
import { getPermitResult } from '~/server/helpers/helpers';

const Home: NextPage = () => {
  const { workType, workOptions, permitResults, setWorkType, setResult } =
    useStore((state) => state);

  useEffect(() => {
    if (!workType) {
      return;
    }

    const permitResults = getPermitResult(workType, workOptions);
    setResult(permitResults);

    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [workType, workOptions]);

  const handleFormSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    // TODO: Connect DB
    // try {
    //   await api.permits.create({
    //     workType,
    //     workOptions,
    //     results,
    //   });
    //   setResult('Data submitted successfully');
    // } catch (error) {
    //   setResult('Error submitting data');
    // }
    return;
  };

  return (
    <>
      <Head>
        <title>T3 App Sample</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#02326d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <div className="w-96 space-y-5 rounded-xl bg-white p-8 shadow-lg">
            <h1 className="text-center text-2xl font-bold text-blue-700">
              Permit Finder
            </h1>
            <form onSubmit={handleFormSubmit} className="space-y-5">
              <WorkTypeView onChange={setWorkType} />
              {workType.length > 0 && <WorkOptionsView />}

              {/* <button
                type="submit"
                className="w-full rounded bg-blue-700 px-4 py-2 text-lg text-white hover:bg-blue-800"
              >
                Submit
              </button> */}
            </form>
            <p className="text-xl text-blue-700">{permitResults}</p>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
